"""
Django settings for dj_jukebox project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import logging
import os
from pathlib import Path

import dj_database_url
from dotenv import load_dotenv
load_dotenv()

try:
    import truststore
except ImportError:
    truststore = None
else:
    # Use the macOS trust store so corporate TLS interception certs work with requests/allauth.
    truststore.inject_into_ssl()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def env_bool(name, default=False):
    value = os.environ.get(name)
    if value is None:
        return default
    return value.strip().lower() in {"1", "true", "yes", "on"}


def env_list(name, default=""):
    raw = os.environ.get(name, default)
    return [item.strip() for item in raw.split(",") if item.strip()]


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    "SECRET_KEY",
    "django-insecure-ca9=grerq8vy+uz-b=k0t$-u1ovz=u%=1%o1va_sngsi4z7sdp",
)

STRIPE_PUBLIC_KEY = os.environ.get('STRIPE_PUBLIC_KEY')
STRIPE_SECRET_KEY = os.environ.get('STRIPE_SECRET_KEY')
STRIPE_WEBHOOK_SECRET = os.environ.get('STRIPE_WEBHOOK_SECRET')
SPOTIFY_CLIENT_ID     = os.environ.get("SPOTIFY_CLIENT_ID")
SPOTIFY_CLIENT_SECRET = os.environ.get("SPOTIFY_CLIENT_SECRET")
SPOTIFY_AUTH_FOR_ALL = env_bool("SPOTIFY_AUTH_FOR_ALL", default=False)

# yt-dlp cookie authentication (needed to bypass YouTube bot detection)
# YTDLP_COOKIES_B64: base64-encoded Netscape cookies.txt (for ephemeral filesystems like Render)
# YTDLP_COOKIES_FILE: direct path to cookies.txt (local dev or persistent disk)
# YTDLP_COOKIES_FROM_BROWSER: browser name ('chrome', 'firefox') — local dev only
_ytdlp_cookies_b64 = os.environ.get('YTDLP_COOKIES_B64', '')
if _ytdlp_cookies_b64:
    import base64, tempfile
    _cookies_dir = os.path.join(tempfile.gettempdir(), 'ytdlp')
    os.makedirs(_cookies_dir, exist_ok=True)
    _cookies_path = os.path.join(_cookies_dir, 'cookies.txt')
    with open(_cookies_path, 'wb') as f:
        f.write(base64.b64decode(_ytdlp_cookies_b64))
    YTDLP_COOKIES_FILE = _cookies_path
else:
    YTDLP_COOKIES_FILE = os.environ.get('YTDLP_COOKIES_FILE', '')
YTDLP_COOKIES_FROM_BROWSER = os.environ.get('YTDLP_COOKIES_FROM_BROWSER', '')

# Audio analysis runtime limits (important on Render free instances)
ENABLE_YTDLP_FALLBACK = env_bool('ENABLE_YTDLP_FALLBACK', default=True)
_analysis_is_production = os.environ.get("APP_ENV", os.environ.get("DJANGO_ENV", "development")).strip().lower() in {"production", "prod"}
ANALYZE_YTDLP_PER_ATTEMPT_TIMEOUT = int(
    os.environ.get('ANALYZE_YTDLP_PER_ATTEMPT_TIMEOUT', '8' if _analysis_is_production else '25')
)
ANALYZE_YTDLP_MAX_WALL_SECONDS = int(
    os.environ.get('ANALYZE_YTDLP_MAX_WALL_SECONDS', '18' if _analysis_is_production else '60')
)
YTDLP_BOT_COOLDOWN_SECONDS = int(os.environ.get('YTDLP_BOT_COOLDOWN_SECONDS', '900'))
ANALYZE_AUDIO_SECONDS = int(
    os.environ.get('ANALYZE_AUDIO_SECONDS', '20' if _analysis_is_production else '45')
)
ANALYZE_AUDIO_SAMPLE_RATE = int(
    os.environ.get('ANALYZE_AUDIO_SAMPLE_RATE', '16000' if _analysis_is_production else '22050')
)

GOOGLE_CLIENT_ID = os.environ.get("GOOGLE_CLIENT_ID")
GOOGLE_CLIENT_SECRET = os.environ.get("GOOGLE_CLIENT_SECRET")

APP_ENV = os.environ.get("APP_ENV", os.environ.get("DJANGO_ENV", "development")).strip().lower()
IS_PRODUCTION = APP_ENV in {"production", "prod"}

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env_bool("DEBUG", default=not IS_PRODUCTION)

LOG_LEVEL = os.environ.get("LOG_LEVEL", "DEBUG" if DEBUG else "INFO").upper()
LOG_FILE_PATH = os.environ.get("LOG_FILE_PATH", str(BASE_DIR / "server.log"))

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
        'file': {
            'class': 'logging.FileHandler',
            'filename': LOG_FILE_PATH,
            'encoding': 'utf-8',
        },
    },
    'root': {
        'handlers': ['console', 'file'],
        'level': LOG_LEVEL,
    },
    'loggers': {
        'allauth': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
        'django.db.backends': {
            'handlers': ['console', 'file'],
            'level': 'WARNING',
            'propagate': False,
        },
        'numba': {
            'handlers': ['console', 'file'],
            'level': 'WARNING',
            'propagate': False,
        },
        'llvmlite': {
            'handlers': ['console', 'file'],
            'level': 'WARNING',
            'propagate': False,
        },
    },
}

ALLOWED_HOSTS = env_list("ALLOWED_HOSTS", "127.0.0.1,localhost")

RENDER_EXTERNAL_HOSTNAME = os.environ.get("RENDER_EXTERNAL_HOSTNAME")
if RENDER_EXTERNAL_HOSTNAME and RENDER_EXTERNAL_HOSTNAME not in ALLOWED_HOSTS:
    ALLOWED_HOSTS.append(RENDER_EXTERNAL_HOSTNAME)


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'django_extensions',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.spotify',
    'allauth.socialaccount.providers.google',
    'jukebox',
]

AUTH_USER_MODEL = 'jukebox.User'

SITE_ID = 1
SITE_DOMAIN = os.environ.get("SITE_DOMAIN", RENDER_EXTERNAL_HOSTNAME or "127.0.0.1:8000")
SITE_NAME = os.environ.get("SITE_NAME", SITE_DOMAIN)

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'jukebox.middleware.DefaultLanguageMiddleware',  # força català per defecte
    'django.middleware.locale.LocaleMiddleware',  # i18n: detecta i aplica idioma
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    "allauth.account.middleware.AccountMiddleware",
]

ROOT_URLCONF = 'dj_jukebox.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'jukebox' / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.template.context_processors.i18n',  # i18n: idioma actual disponible als templates
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'jukebox.context_processors.selected_party',
                'jukebox.context_processors.user_avatar',
                'jukebox.context_processors.unread_notifications_count',
                'jukebox.context_processors.social_login_providers',
            ],
        },
    },
]

WSGI_APPLICATION = 'dj_jukebox.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': dj_database_url.config(
        default=f"sqlite:///{BASE_DIR / 'db.sqlite3'}",
        conn_max_age=600,
        conn_health_checks=True,
    )
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'ca'  # Idioma per defecte: català
TIME_ZONE = 'Europe/Madrid'  # Zona horària per Catalunya/Espanya
USE_I18N = True  # Activar internacionalització
USE_L10N = True  # Activar localització (formats de data/número)
USE_TZ = True    # Activar zones horàries

LANGUAGES = [
    ('ca', 'Català'),
    ('en', 'English'),
]

LOCALE_PATHS = [
    BASE_DIR / 'locale',
    BASE_DIR / 'jukebox' / 'locale',
]

# Configuració per guardar preferència d'idioma
LANGUAGE_COOKIE_NAME = 'django_language'
LANGUAGE_COOKIE_AGE = 31536000  # 1 any (en segons)
LANGUAGE_COOKIE_PATH = '/'
LANGUAGE_COOKIE_HTTPONLY = env_bool("LANGUAGE_COOKIE_HTTPONLY", default=False)
LANGUAGE_COOKIE_SAMESITE = 'Lax'


# Cache
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'dj-jukebox',
    }
}

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

STATICFILES_DIRS = [
    BASE_DIR / 'jukebox' / 'static',
]

# Media files (User uploads)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

CSRF_TRUSTED_ORIGINS = env_list(
    "CSRF_TRUSTED_ORIGINS",
    "http://127.0.0.1:8000,http://localhost:8000",
)

if RENDER_EXTERNAL_HOSTNAME:
    render_origin = f"https://{RENDER_EXTERNAL_HOSTNAME}"
    if render_origin not in CSRF_TRUSTED_ORIGINS:
        CSRF_TRUSTED_ORIGINS.append(render_origin)

SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
USE_X_FORWARDED_HOST = env_bool("USE_X_FORWARDED_HOST", default=IS_PRODUCTION)

# django-ipware: llegeix la IP real del client des del header que posa el proxy.
# Necessari perquè allauth pugui fer rate limiting al signup/login en producció.
IPWARE_META_PRECEDENCE_ORDER = (
    'HTTP_X_FORWARDED_FOR',
    'HTTP_X_REAL_IP',
    'REMOTE_ADDR',
)

SESSION_COOKIE_SECURE = env_bool("SESSION_COOKIE_SECURE", default=IS_PRODUCTION)
CSRF_COOKIE_SECURE = env_bool("CSRF_COOKIE_SECURE", default=IS_PRODUCTION)
SESSION_COOKIE_HTTPONLY = env_bool("SESSION_COOKIE_HTTPONLY", default=True)
CSRF_COOKIE_HTTPONLY = env_bool("CSRF_COOKIE_HTTPONLY", default=False)
SECURE_SSL_REDIRECT = env_bool("SECURE_SSL_REDIRECT", default=IS_PRODUCTION)
SECURE_HSTS_SECONDS = int(os.environ.get("SECURE_HSTS_SECONDS", "31536000" if IS_PRODUCTION else "0"))
SECURE_HSTS_INCLUDE_SUBDOMAINS = env_bool("SECURE_HSTS_INCLUDE_SUBDOMAINS", default=IS_PRODUCTION)
SECURE_HSTS_PRELOAD = env_bool("SECURE_HSTS_PRELOAD", default=False)
SECURE_REFERRER_POLICY = os.environ.get("SECURE_REFERRER_POLICY", "same-origin")
SECURE_CONTENT_TYPE_NOSNIFF = env_bool("SECURE_CONTENT_TYPE_NOSNIFF", default=True)
X_FRAME_OPTIONS = os.environ.get("X_FRAME_OPTIONS", "DENY")

if IS_PRODUCTION and SECRET_KEY.startswith("django-insecure-"):
    raise RuntimeError("SECRET_KEY insegura en produccio. Defineix una clau segura a l'entorn.")

if IS_PRODUCTION and not STRIPE_WEBHOOK_SECRET:
    raise RuntimeError("STRIPE_WEBHOOK_SECRET no configurat en producció.")

LOGIN_REDIRECT_URL = '/'
ACCOUNT_SIGNUP_REDIRECT_URL = '/'


LOGIN_URL = '/login/'

SOCIALACCOUNT_PROVIDERS = {
    'spotify': {
        'SCOPE': [
            'user-read-email',
            'user-read-private',
            'playlist-read-private',
            'playlist-read-collaborative',
            'playlist-modify-public',
            'playlist-modify-private',
            'streaming',
            'user-read-playback-state',
            'user-modify-playback-state',
        ],
        'AUTH_PARAMS': {
            'show_dialog': True,
        },
    },
    'google': {
        'SCOPE': [
            'profile',
            'email',
        ],
        'AUTH_PARAMS': {
            'access_type': 'online',
        },
    }
}

ACCOUNT_LOGIN_METHODS = {"email", "username"}   # Pots posar només "email" si vols login només amb email
ACCOUNT_SIGNUP_FIELDS = ["email*", "username*", "password1*", "password2*"]

ACCOUNT_UNIQUE_EMAIL = True
SOCIALACCOUNT_QUERY_EMAIL = True
SOCIALACCOUNT_AUTO_SIGNUP = True
ACCOUNT_EMAIL_VERIFICATION = "mandatory"  # Registres amb email han de verificar obligatòriament
SOCIALACCOUNT_EMAIL_VERIFICATION = "none"  # Logins socials (Spotify) no necessiten verificació
SOCIALACCOUNT_STORE_TOKENS = True
SOCIALACCOUNT_EMAIL_AUTHENTICATION = True  # Permet connectar comptes amb el mateix email
SOCIALACCOUNT_EMAIL_AUTHENTICATION_AUTO_CONNECT = True  # Auto-connecta si l'email ja existeix


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

#Email Conf
EMAIL_BACKEND = os.environ.get(
    "EMAIL_BACKEND",
    "django.core.mail.backends.smtp.EmailBackend"
    if IS_PRODUCTION
    else "django.core.mail.backends.console.EmailBackend",
)
EMAIL_HOST = os.environ.get("EMAIL_HOST", "smtp.gmail.com")
EMAIL_PORT = int(os.environ.get("EMAIL_PORT", "465"))
EMAIL_USE_TLS = env_bool("EMAIL_USE_TLS", default=False)
EMAIL_USE_SSL = env_bool("EMAIL_USE_SSL", default=True)
EMAIL_HOST_USER = os.environ.get("GMAIL_USER")
EMAIL_HOST_PASSWORD = os.environ.get("GMAIL_APP_PASSWORD")
DEFAULT_FROM_EMAIL = os.environ.get("DEFAULT_FROM_EMAIL", "DJ Jukebox <djkram@gmail.com>")
