# Generated by Django 5.2.4 on 2025-07-08 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('artist', models.CharField(max_length=200)),
                ('spotify_id', models.CharField(max_length=100, unique=True)),
                ('votes', models.IntegerField(default=0)),
                ('played', models.BooleanField(default=False)),
            ],
        ),
    ]
