# Generated by Django 5.2.4 on 2025-07-22 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jukebox', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='has_played',
            field=models.BooleanField(default=False),
        ),
    ]
