# Generated by Django 4.2.23 on 2025-07-11 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jukebox', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spotify_id', models.CharField(max_length=128, unique=True)),
                ('name', models.CharField(max_length=256)),
                ('owner', models.CharField(max_length=128)),
            ],
        ),
        migrations.AlterField(
            model_name='song',
            name='spotify_id',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date', models.DateTimeField()),
                ('playlist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jukebox.playlist')),
            ],
        ),
        migrations.AddField(
            model_name='song',
            name='party',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='jukebox.party'),
        ),
    ]
