# Generated by Django 4.2.23 on 2025-07-12 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jukebox', '0002_playlist_alter_song_spotify_id_party_song_party'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='code',
            field=models.CharField(default='', editable=False, max_length=12, unique=True),
        ),
    ]
