# Generated by Django 5.2.4 on 2025-07-23 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jukebox', '0002_song_has_played'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='bpm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='key',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
