# Generated by Django 4.2.23 on 2026-03-13 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jukebox', '0003_song_bpm_song_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='album_image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
