# Generated by Django 5.2.4 on 2025-07-16 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jukebox', '0005_vote_votepackage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vote', to='jukebox.song'),
        ),
    ]
