# Generated by Django 4.2.23 on 2026-03-15 14:18

from django.db import migrations, models


def remove_duplicate_votes(apps, schema_editor):
    """
    Elimina vots duplicats mantenint només el més recent de cada combinació user-song-party.
    """
    Vote = apps.get_model('jukebox', 'Vote')

    # Obtenir tots els vots ordenats per created_at
    all_votes = Vote.objects.all().order_by('user_id', 'song_id', 'party_id', '-created_at')

    seen = set()
    votes_to_delete = []

    for vote in all_votes:
        key = (vote.user_id, vote.song_id, vote.party_id)
        if key in seen:
            votes_to_delete.append(vote.id)
        else:
            seen.add(key)

    # Eliminar els duplicats
    if votes_to_delete:
        Vote.objects.filter(id__in=votes_to_delete).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('jukebox', '0006_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='vote_type',
            field=models.CharField(choices=[('like', "M'agrada"), ('dislike', "No m'agrada")], default='like', max_length=10),
        ),
        migrations.RunPython(remove_duplicate_votes, migrations.RunPython.noop),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together={('user', 'song', 'party')},
        ),
    ]
