# Generated by Django 4.2.23 on 2026-03-17 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jukebox', '0007_vote_vote_type_alter_vote_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='preview_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
