# Generated by Django 4.2.23 on 2026-03-17 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jukebox', '0008_song_preview_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='initial_coins_per_user',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
