# Generated by Django 4.2.23 on 2026-03-17 14:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jukebox', '0009_party_initial_coins_per_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='party',
            old_name='initial_coins_per_user',
            new_name='free_coins_per_user',
        ),
        migrations.CreateModel(
            name='PartyCoinsGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coins_granted', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.CharField(default='free_coins', max_length=100)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jukebox.party')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
