# Generated by Django 4.2.23 on 2026-03-19 14:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jukebox', '0010_rename_initial_coins_per_user_party_free_coins_per_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='auto_sync_playlist',
            field=models.BooleanField(default=False, help_text='Sincronitzar automàticament amb Spotify cada 5 minuts'),
        ),
        migrations.AddField(
            model_name='party',
            name='last_sync_at',
            field=models.DateTimeField(blank=True, help_text='Última sincronització exitosa', null=True),
        ),
        migrations.AddField(
            model_name='party',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='Creador de la festa (necessari per Spotify sync)', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
