# Generated by Django 4.2.23 on 2026-03-19 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jukebox', '0011_party_auto_sync_playlist_party_last_sync_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='auto_analyze_audio',
            field=models.BooleanField(default=False, help_text='Analitzar automàticament àudio cada 5 minuts'),
        ),
        migrations.AddField(
            model_name='party',
            name='last_analyze_at',
            field=models.DateTimeField(blank=True, help_text='Última anàlisi automàtica', null=True),
        ),
    ]
