# Generated by Django 4.2.23 on 2026-03-19 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jukebox', '0012_party_auto_analyze_audio_party_last_analyze_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='vote_type',
            field=models.CharField(choices=[('like', "M'agrada"), ('dislike', "No m'agrada"), ('skip', 'Passar')], default='like', max_length=10),
        ),
    ]
