# Generated by Django 4.2.23 on 2026-04-05 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jukebox', '0017_alter_party_party_status_hidden'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='cover_image',
            field=models.ImageField(blank=True, help_text='Imatge de portada de la festa', null=True, upload_to='party_covers/'),
        ),
        migrations.AddField(
            model_name='party',
            name='is_public',
            field=models.BooleanField(default=True, help_text='Festa pública (llistada) o privada (no llistada)'),
        ),
        migrations.AddField(
            model_name='party',
            name='require_join_code',
            field=models.BooleanField(default=False, help_text='Requerir codi per unir-se a la festa'),
        ),
    ]
