# Generated by Django 5.2.1 on 2026-04-21 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jukebox', '0018_party_cover_image_party_is_public_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='allow_song_requests',
            field=models.BooleanField(default=True, help_text='Permetre als usuaris demanar cançons noves (es paguen amb Coins)'),
        ),
        migrations.AlterField(
            model_name='party',
            name='code',
            field=models.CharField(default='', max_length=12, unique=True),
        ),
    ]
