# Generated by Django 5.2.1 on 2026-04-28 17:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jukebox', '0019_party_allow_song_requests'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='djs',
            field=models.ManyToManyField(blank=True, help_text='Usuaris amb rol de DJ per a aquesta festa', related_name='dj_parties', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='party',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='party',
            name='location_name',
            field=models.CharField(blank=True, default='', help_text='Nom o adreça de la localització', max_length=255),
        ),
        migrations.AddField(
            model_name='party',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
