# Generated by Django 5.2.1 on 2026-04-28 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jukebox', '0020_party_location_and_djs'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='location_radius_km',
            field=models.PositiveIntegerField(default=0, help_text='Radi en km per restringir accés per ubicació (0 = sense restricció)'),
        ),
    ]
