# Generated by Django 5.2.1 on 2026-04-28 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jukebox', '0021_party_location_radius'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='party_status',
            field=models.CharField(choices=[('hidden', 'Festa oculta'), ('party_visible', 'Festa visible (sense llista)'), ('show_party', 'Mostrar festa i llista'), ('requests_open', 'Obrir peticions'), ('djjukebox_active', 'Iniciar Jukebox'), ('finished', 'Acabar festa')], default='hidden', max_length=20),
        ),
    ]
