# Generated by Django 5.2.1 on 2026-05-05 18:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jukebox', '0022_party_visible_status'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='song',
            unique_together={('party', 'spotify_id')},
        ),
        migrations.AlterField(
            model_name='party',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='Creador de la festa (necessari per Spotify sync)', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='votepackage',
            name='payment_id',
            field=models.CharField(blank=True, max_length=128, null=True, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='partycoinsgrant',
            unique_together={('user', 'party', 'reason')},
        ),
        migrations.RemoveField(
            model_name='song',
            name='votes',
        ),
    ]
