# Generated by Django 5.2.1 on 2026-05-09 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jukebox', '0025_song_played_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='is_read',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='song',
            name='has_played',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='songrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendent'), ('accepted', 'Acceptada'), ('rejected', 'Rebutjada')], db_index=True, default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='vote',
            name='vote_type',
            field=models.CharField(choices=[('like', "M'agrada"), ('dislike', "No m'agrada"), ('skip', 'Passar')], db_index=True, default='like', max_length=10),
        ),
    ]
