# Generated by Django 5.2.1 on 2026-05-19 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jukebox', '0027_song_acousticness_song_danceability_song_duration_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'is_read'], name='jukebox_not_user_id_f8ebf9_idx'),
        ),
        migrations.AddIndex(
            model_name='song',
            index=models.Index(fields=['party', 'has_played'], name='jukebox_son_party_i_64289e_idx'),
        ),
        migrations.AddIndex(
            model_name='songrequest',
            index=models.Index(fields=['party', 'status'], name='jukebox_son_party_i_a593d4_idx'),
        ),
        migrations.AddIndex(
            model_name='vote',
            index=models.Index(fields=['party', 'vote_type'], name='jukebox_vot_party_i_f9c77d_idx'),
        ),
        migrations.AddIndex(
            model_name='vote',
            index=models.Index(fields=['party', 'user'], name='jukebox_vot_party_i_012916_idx'),
        ),
        migrations.AddIndex(
            model_name='vote',
            index=models.Index(fields=['party', 'created_at'], name='jukebox_vot_party_i_b949bd_idx'),
        ),
    ]
