# Generated by Django 5.2.1 on 2026-05-19 21:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jukebox', '0028_add_composite_indexes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='party',
            name='owner',
        ),
        migrations.AddField(
            model_name='party',
            name='owners',
            field=models.ManyToManyField(blank=True, help_text="Usuaris amb rol d'owner de la festa", related_name='owned_parties', to=settings.AUTH_USER_MODEL),
        ),
    ]
