# Generated by Codex on 2026-06-07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jukebox', '0029_party_owner_fk_to_m2m'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SongSwipeSkip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jukebox.party')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swipe_skips', to='jukebox.song')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [
                    models.Index(fields=['party', 'user'], name='jukebox_son_party_i_11ca89_idx'),
                    models.Index(fields=['party', 'created_at'], name='jukebox_son_party_i_356ddc_idx'),
                ],
                'unique_together': {('user', 'song', 'party')},
            },
        ),
    ]
