# Generated by Django 5.2.1 on 2026-06-09 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jukebox', '0030_songswipeskip'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='songswipeskip',
            new_name='jukebox_son_party_i_859d24_idx',
            old_name='jukebox_son_party_i_11ca89_idx',
        ),
        migrations.RenameIndex(
            model_name='songswipeskip',
            new_name='jukebox_son_party_i_39367b_idx',
            old_name='jukebox_son_party_i_356ddc_idx',
        ),
        migrations.AddField(
            model_name='songrequest',
            name='coins_charged',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('song_accepted', 'Cançó acceptada'), ('song_queued', 'Cançó a la maleta'), ('song_loaded', 'Cançó carregada'), ('song_rejected', 'Cançó rebutjada'), ('song_played', 'Cançó reproduïda'), ('coins_purchased', 'Coins comprats'), ('coins_received', 'Coins rebuts')], max_length=20),
        ),
        migrations.AlterField(
            model_name='songrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendent'), ('queued', 'A la maleta'), ('accepted', 'Acceptada'), ('rejected', 'Rebutjada')], db_index=True, default='pending', max_length=10),
        ),
    ]
