# Generated by Django 5.2.1 on 2026-06-09 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jukebox', '0031_songrequest_queued_coins_charged'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('song_accepted', 'Cançó posada a la sessió'), ('song_queued', 'Cançó a la Maleta'), ('song_loaded', 'LOAD: Posada a la sessió'), ('song_rejected', 'Petició no acceptada'), ('song_played', 'Cançó reproduïda'), ('coins_purchased', 'Coins comprats'), ('coins_received', 'Coins rebuts')], max_length=20),
        ),
        migrations.AlterField(
            model_name='songrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Demanada'), ('queued', 'Afegida a la Maleta'), ('accepted', 'Posada a la sessió'), ('rejected', 'Rebutjada')], db_index=True, default='pending', max_length=10),
        ),
    ]
