# Generated by Django 5.2.1 on 2026-06-14 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jukebox', '0032_alter_notification_type_alter_songrequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='finished_at',
            field=models.DateTimeField(blank=True, help_text='Moment exacte en què la festa va ser marcada com acabada', null=True),
        ),
    ]
